# Networking
CONFIG_NETWORKING=y
#CONFIG_NET_DRIVERS=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_ARP=y
CONFIG_NET_UDP=y

CONFIG_NET_PKT_RX_COUNT=8
CONFIG_NET_PKT_TX_COUNT=8
CONFIG_NET_MAX_CONTEXTS=16
CONFIG_NET_MAX_CONN=16
CONFIG_NET_CONTEXT_SYNC_RECV=y
CONFIG_NET_TX_STACK_SIZE=4096
CONFIG_NET_RX_STACK_SIZE=4096
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_SOCKETS_POLL_MAX=12
CONFIG_NET_BUF_RX_COUNT=16
CONFIG_NET_BUF_TX_COUNT=16
CONFIG_NET_BUF_DATA_SIZE=128
CONFIG_NET_TC_TX_COUNT=1
CONFIG_ENTROPY_GENERATOR=y

# log
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=0
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=4096


# shell
CONFIG_SHELL=y
CONFIG_KERNEL_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_BACKEND_SERIAL_INTERRUPT_DRIVEN=n
CONFIG_SHELL_THREAD_PRIORITY_OVERRIDE=y
CONFIG_SHELL_THREAD_PRIORITY=0

# net
CONFIG_NET_IPV4_AUTO=n
CONFIG_NET_IPV6=n
CONFIG_NET_DHCPV4=y
CONFIG_NET_DHCPV4_ACCEPT_UNICAST=n
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_PHY_VERIFY_DEVICE_IDENTIFICATION=y
CONFIG_NET_LOG=y
CONFIG_ETHERNET_LOG_LEVEL_DBG=y
CONFIG_NET_DHCPV4_LOG_LEVEL_DBG=y

# Static IP configuration
#CONFIG_NET_CONFIG_SETTINGS=y
#CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.2.42"
#CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.255.0"
#CONFIG_NET_CONFIG_MY_IPV4_GW="192.168.2.1"

# PHY driver
CONFIG_GPIO=y
CONFIG_PHY_MICROCHIP_VSC8541=y

# Memory
CONFIG_HEAP_MEM_POOL_SIZE=200000
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=100000

CONFIG_MAIN_STACK_SIZE=8192

# Size optimization
CONFIG_SIZE_OPTIMIZATIONS=y

CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_EVENTFD=y
CONFIG_POSIX_API=y

# C++ support
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_CPP_EXCEPTIONS=n
CONFIG_CPP_RTTI=n

# open62541
CONFIG_OPEN62541=y
CONFIG_OPEN62541_ENABLE_DISCOVERY_SEMAPHORE=n
CONFIG_OPEN62541_MULTITHREADING=0
CONFIG_OPEN62541_NAMESPACE_ZERO="REDUCED"
CONFIG_OPEN62541_ENABLE_PUBSUB=n
CONFIG_OPEN62541_ENABLE_PUBSUB_INFORMATIONMODEL=n
CONFIG_OPEN62541_ENABLE_SUBSCRIPTIONS_EVENTS=n
CONFIG_OPEN62541_ENABLE_SUBSCRIPTIONS=y
CONFIG_OPEN62541_ENABLE_HISTORIZING=n
CONFIG_OPEN62541_ENABLE_JSON_ENCODING=n
CONFIG_OPEN62541_ENABLE_DIAGNOSTICS=n
CONFIG_OPEN62541_ENABLE_DISCOVERY=n
CONFIG_OPEN62541_ENABLE_STATUSCODE_DESCRIPTIONS=n
CONFIG_OPEN62541_ENABLE_NODESET_COMPILER_DESCRIPTIONS=n
CONFIG_OPEN62541_ENABLE_DEBUG_SANITIZER=n
CONFIG_OPEN62541_ENABLE_XML_ENCODING=n
CONFIG_OPEN62541_ENABLE_METHODCALLS=n
CONFIG_OPEN62541_ENABLE_NODEMANAGEMENT=n
